//! # SubStream Pull-Tester CLI
//!
//! A local simulation tool for merchants integrating the SubStream pull-payment
//! protocol. It replicates the Soroban VM billing loop without requiring a live
//! testnet connection, letting Web2 developers iterate on their integration in
//! seconds rather than waiting for block confirmations.
//!
//! ## Safety
//! All keys generated by this tool are clearly marked as **MOCK** keys and will
//! never be submitted to any Stellar network. The tool has no network I/O.
//!
//! ## Usage
//! ```
//! pull-tester subscribe --merchant GMERCHANT... --subscriber GSUB... --plan-id 1 \
//!   --billing-amount 100 --billing-cycle 2592000
//!
//! pull-tester advance --seconds 2592000
//!
//! pull-tester pull --merchant GMERCHANT... --subscriber GSUB...
//!
//! pull-tester status --subscriber GSUB...
//! ```

use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

// ── Constants (mirrors contracts/substream_contracts/src/lib.rs) ─────────────

const FREE_TRIAL_DURATION: u64 = 7 * 24 * 60 * 60; // 7 days
const GRACE_PERIOD: u64 = 24 * 60 * 60; // 24 hours
const MINIMUM_FLOW_DURATION: u64 = 24 * 60 * 60; // 24 hours
const PRECISION_MULTIPLIER: i128 = 1_000_000_000;

// ── State file ────────────────────────────────────────────────────────────────

fn state_path() -> PathBuf {
    PathBuf::from(".pull-tester-state.json")
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
struct SimState {
    /// Current simulated ledger timestamp (Unix seconds).
    pub ledger_timestamp: u64,
    /// Registered plans: merchant_address -> Vec<Plan>
    pub plans: HashMap<String, Vec<Plan>>,
    /// Active billing cycles: "subscriber:merchant" -> BillingCycle
    pub billing_cycles: HashMap<String, BillingCycle>,
    /// Token balances: address -> balance
    pub balances: HashMap<String, i128>,
    /// Pull history for audit trail
    pub pull_history: Vec<PullRecord>,
}

impl SimState {
    fn load() -> Self {
        let path = state_path();
        if path.exists() {
            let data = fs::read_to_string(&path).expect("failed to read state file");
            serde_json::from_str(&data).expect("failed to parse state file")
        } else {
            let mut s = SimState::default();
            s.ledger_timestamp = 1_000_000; // arbitrary non-zero start
            s
        }
    }

    fn save(&self) {
        let data = serde_json::to_string_pretty(self).expect("failed to serialise state");
        fs::write(state_path(), data).expect("failed to write state file");
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Plan {
    pub plan_id: u32,
    pub name: String,
    pub billing_amount: i128,
    pub billing_cycle: u64,
    pub has_trial: bool,
    pub trial_duration: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct BillingCycle {
    pub subscriber: String,
    pub merchant: String,
    pub plan_id: u32,
    pub billing_amount: i128,
    pub billing_cycle: u64,
    pub next_billing_date: u64,
    pub status: SubscriptionStatus,
    pub dunning_start: u64,
    pub subscribed_at: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
enum SubscriptionStatus {
    Trial,
    Active,
    PastDue,
    Canceled,
}

impl std::fmt::Display for SubscriptionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SubscriptionStatus::Trial => write!(f, "Trial"),
            SubscriptionStatus::Active => write!(f, "Active"),
            SubscriptionStatus::PastDue => write!(f, "PastDue"),
            SubscriptionStatus::Canceled => write!(f, "Canceled"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PullRecord {
    pub merchant: String,
    pub subscriber: String,
    pub amount: i128,
    pub pulled_at: u64,
    pub cycle_number: u64,
    pub receipt_hash: String,
}

// ── CLI definition ────────────────────────────────────────────────────────────

#[derive(Parser, Debug)]
#[command(
    name = "pull-tester",
    version = "0.1.0",
    about = "SubStream merchant pull-payment local simulator",
    long_about = "Simulate the SubStream billing loop locally without a live testnet.\n\
                  All keys are MOCK keys — no network requests are made."
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Register a billing plan for a merchant
    RegisterPlan {
        #[arg(long)]
        merchant: String,
        #[arg(long)]
        plan_id: u32,
        #[arg(long, default_value = "Standard Plan")]
        name: String,
        /// Billing amount in token units
        #[arg(long)]
        billing_amount: i128,
        /// Billing cycle duration in seconds (e.g. 2592000 = 30 days)
        #[arg(long)]
        billing_cycle: u64,
        /// Whether this plan includes a free trial
        #[arg(long, default_value_t = false)]
        has_trial: bool,
        /// Trial duration in seconds (default: 7 days)
        #[arg(long, default_value_t = FREE_TRIAL_DURATION)]
        trial_duration: u64,
    },

    /// Subscribe a user to a merchant plan
    Subscribe {
        #[arg(long)]
        subscriber: String,
        #[arg(long)]
        merchant: String,
        #[arg(long)]
        plan_id: u32,
        /// Initial token balance to fund the subscription
        #[arg(long, default_value_t = 1_000_000)]
        initial_balance: i128,
    },

    /// Advance the simulated ledger clock
    Advance {
        /// Number of seconds to advance
        #[arg(long)]
        seconds: u64,
    },

    /// Execute a merchant pull (collect one billing cycle)
    Pull {
        #[arg(long)]
        merchant: String,
        #[arg(long)]
        subscriber: String,
    },

    /// Show the current subscription status for a subscriber
    Status {
        #[arg(long)]
        subscriber: String,
    },

    /// Show the current simulated ledger timestamp
    Ledger,

    /// Reset all simulation state
    Reset,

    /// Dump the full state as JSON
    Dump,
}

// ── Command handlers ──────────────────────────────────────────────────────────

fn cmd_register_plan(
    state: &mut SimState,
    merchant: String,
    plan_id: u32,
    name: String,
    billing_amount: i128,
    billing_cycle: u64,
    has_trial: bool,
    trial_duration: u64,
) {
    let plans = state.plans.entry(merchant.clone()).or_default();
    if plans.iter().any(|p| p.plan_id == plan_id) {
        eprintln!("ERROR: plan_id {} already exists for merchant {}", plan_id, merchant);
        std::process::exit(1);
    }
    plans.push(Plan {
        plan_id,
        name: name.clone(),
        billing_amount,
        billing_cycle,
        has_trial,
        trial_duration,
    });

    let result = serde_json::json!({
        "event": "PlanRegistered",
        "merchant": merchant,
        "plan_id": plan_id,
        "name": name,
        "billing_amount": billing_amount,
        "billing_cycle_seconds": billing_cycle,
        "has_trial": has_trial,
        "trial_duration_seconds": trial_duration,
        "registered_at": state.ledger_timestamp,
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_subscribe(
    state: &mut SimState,
    subscriber: String,
    merchant: String,
    plan_id: u32,
    initial_balance: i128,
) {
    let key = format!("{}:{}", subscriber, merchant);
    if state.billing_cycles.contains_key(&key) {
        eprintln!("ERROR: subscription already exists for {}:{}", subscriber, merchant);
        std::process::exit(1);
    }

    let plans = state.plans.get(&merchant).cloned().unwrap_or_default();
    let plan = plans.iter().find(|p| p.plan_id == plan_id).cloned().unwrap_or_else(|| {
        eprintln!("ERROR: plan_id {} not found for merchant {}", plan_id, merchant);
        std::process::exit(1);
    });

    let now = state.ledger_timestamp;
    let (status, next_billing) = if plan.has_trial {
        (SubscriptionStatus::Trial, now + plan.trial_duration)
    } else {
        (SubscriptionStatus::Active, now + plan.billing_cycle)
    };

    // Fund the subscriber's mock balance
    *state.balances.entry(subscriber.clone()).or_insert(0) += initial_balance;

    state.billing_cycles.insert(key, BillingCycle {
        subscriber: subscriber.clone(),
        merchant: merchant.clone(),
        plan_id,
        billing_amount: plan.billing_amount,
        billing_cycle: plan.billing_cycle,
        next_billing_date: next_billing,
        status: status.clone(),
        dunning_start: 0,
        subscribed_at: now,
    });

    let result = serde_json::json!({
        "event": "Subscribed",
        "subscriber": subscriber,
        "merchant": merchant,
        "plan_id": plan_id,
        "status": status.to_string(),
        "next_billing_date": next_billing,
        "initial_balance": initial_balance,
        "subscribed_at": now,
        "note": "MOCK — no network request made",
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_advance(state: &mut SimState, seconds: u64) {
    let old = state.ledger_timestamp;
    state.ledger_timestamp = state.ledger_timestamp.saturating_add(seconds);

    // Auto-convert Trial -> Active when trial period expires
    for cycle in state.billing_cycles.values_mut() {
        if cycle.status == SubscriptionStatus::Trial
            && state.ledger_timestamp >= cycle.next_billing_date
        {
            cycle.status = SubscriptionStatus::Active;
            cycle.next_billing_date =
                state.ledger_timestamp.saturating_add(cycle.billing_cycle);
        }
    }

    let result = serde_json::json!({
        "event": "LedgerAdvanced",
        "from_timestamp": old,
        "to_timestamp": state.ledger_timestamp,
        "seconds_advanced": seconds,
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_pull(state: &mut SimState, merchant: String, subscriber: String) {
    let key = format!("{}:{}", subscriber, merchant);
    let cycle = state.billing_cycles.get(&key).cloned().unwrap_or_else(|| {
        eprintln!("ERROR: no subscription found for {}:{}", subscriber, merchant);
        std::process::exit(1);
    });

    let now = state.ledger_timestamp;

    if cycle.status == SubscriptionStatus::Canceled {
        eprintln!("ERROR: subscription is canceled");
        std::process::exit(1);
    }

    if now < cycle.next_billing_date {
        let remaining = cycle.next_billing_date - now;
        let result = serde_json::json!({
            "error": "billing premature",
            "next_billing_date": cycle.next_billing_date,
            "current_timestamp": now,
            "seconds_until_due": remaining,
        });
        eprintln!("{}", serde_json::to_string_pretty(&result).unwrap());
        std::process::exit(1);
    }

    let amount = cycle.billing_amount;
    let subscriber_balance = state.balances.get(&subscriber).copied().unwrap_or(0);

    if subscriber_balance < amount {
        // Enter dunning / PastDue
        let cycle_mut = state.billing_cycles.get_mut(&key).unwrap();
        if cycle_mut.status != SubscriptionStatus::PastDue {
            cycle_mut.status = SubscriptionStatus::PastDue;
            cycle_mut.dunning_start = now;
        }
        let result = serde_json::json!({
            "error": "insufficient balance — dunning started",
            "subscriber_balance": subscriber_balance,
            "required": amount,
            "dunning_start": now,
            "grace_period_end": now + GRACE_PERIOD,
        });
        eprintln!("{}", serde_json::to_string_pretty(&result).unwrap());
        std::process::exit(1);
    }

    // Deduct from subscriber, credit merchant
    *state.balances.get_mut(&subscriber).unwrap() -= amount;
    *state.balances.entry(merchant.clone()).or_insert(0) += amount;

    // Generate deterministic mock receipt hash
    let receipt_hash = format!(
        "mock-receipt-{}-{}-{}-{}",
        &merchant[..8.min(merchant.len())],
        &subscriber[..8.min(subscriber.len())],
        amount,
        now
    );

    let cycle_number = cycle.billing_cycle;
    let record = PullRecord {
        merchant: merchant.clone(),
        subscriber: subscriber.clone(),
        amount,
        pulled_at: now,
        cycle_number,
        receipt_hash: receipt_hash.clone(),
    };
    state.pull_history.push(record);

    // Update billing cycle
    let cycle_mut = state.billing_cycles.get_mut(&key).unwrap();
    cycle_mut.next_billing_date = now.saturating_add(cycle_mut.billing_cycle);
    if cycle_mut.status == SubscriptionStatus::PastDue {
        cycle_mut.status = SubscriptionStatus::Active;
        cycle_mut.dunning_start = 0;
    }

    let result = serde_json::json!({
        "event": "SubscriptionBilled",
        "subscriber": subscriber,
        "merchant": merchant,
        "amount": amount,
        "billed_at": now,
        "next_billing_date": cycle_mut.next_billing_date,
        "receipt_hash": receipt_hash,
        "cycle_number": cycle_number,
        "subscriber_balance_after": state.balances.get(&subscriber).copied().unwrap_or(0),
        "merchant_balance_after": state.balances.get(&merchant).copied().unwrap_or(0),
        "note": "MOCK — no network request made",
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_status(state: &SimState, subscriber: String) {
    let cycles: Vec<_> = state
        .billing_cycles
        .values()
        .filter(|c| c.subscriber == subscriber)
        .collect();

    if cycles.is_empty() {
        println!("{{\"subscriber\": \"{}\", \"subscriptions\": []}}", subscriber);
        return;
    }

    let subs: Vec<_> = cycles
        .iter()
        .map(|c| {
            let now = state.ledger_timestamp;
            let seconds_until_due = if now < c.next_billing_date {
                c.next_billing_date - now
            } else {
                0
            };
            serde_json::json!({
                "merchant": c.merchant,
                "plan_id": c.plan_id,
                "status": c.status.to_string(),
                "billing_amount": c.billing_amount,
                "billing_cycle_seconds": c.billing_cycle,
                "next_billing_date": c.next_billing_date,
                "seconds_until_due": seconds_until_due,
                "subscriber_balance": state.balances.get(&c.subscriber).copied().unwrap_or(0),
            })
        })
        .collect();

    let result = serde_json::json!({
        "subscriber": subscriber,
        "current_timestamp": state.ledger_timestamp,
        "subscriptions": subs,
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_ledger(state: &SimState) {
    let result = serde_json::json!({
        "ledger_timestamp": state.ledger_timestamp,
        "active_subscriptions": state.billing_cycles.len(),
        "pull_history_count": state.pull_history.len(),
    });
    println!("{}", serde_json::to_string_pretty(&result).unwrap());
}

fn cmd_dump(state: &SimState) {
    println!("{}", serde_json::to_string_pretty(state).unwrap());
}

// ── Entry point ───────────────────────────────────────────────────────────────

fn main() {
    let cli = Cli::parse();
    let mut state = SimState::load();

    match cli.command {
        Commands::RegisterPlan {
            merchant,
            plan_id,
            name,
            billing_amount,
            billing_cycle,
            has_trial,
            trial_duration,
        } => {
            cmd_register_plan(
                &mut state,
                merchant,
                plan_id,
                name,
                billing_amount,
                billing_cycle,
                has_trial,
                trial_duration,
            );
        }
        Commands::Subscribe {
            subscriber,
            merchant,
            plan_id,
            initial_balance,
        } => {
            cmd_subscribe(&mut state, subscriber, merchant, plan_id, initial_balance);
        }
        Commands::Advance { seconds } => {
            cmd_advance(&mut state, seconds);
        }
        Commands::Pull { merchant, subscriber } => {
            cmd_pull(&mut state, merchant, subscriber);
        }
        Commands::Status { subscriber } => {
            cmd_status(&state, subscriber);
        }
        Commands::Ledger => {
            cmd_ledger(&state);
        }
        Commands::Reset => {
            if state_path().exists() {
                fs::remove_file(state_path()).expect("failed to remove state file");
            }
            println!("{{\"event\": \"StateReset\"}}");
            return; // Don't save after reset
        }
        Commands::Dump => {
            cmd_dump(&state);
            return; // Read-only, no save needed
        }
    }

    state.save();
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn fresh_state() -> SimState {
        let mut s = SimState::default();
        s.ledger_timestamp = 1_000_000;
        s
    }

    fn register_basic_plan(state: &mut SimState, merchant: &str) {
        cmd_register_plan(
            state,
            merchant.to_string(),
            1,
            "Basic".to_string(),
            100,
            2_592_000, // 30 days
            false,
            0,
        );
    }

    #[test]
    fn test_register_plan_success() {
        let mut state = fresh_state();
        register_basic_plan(&mut state, "GMERCHANT");
        assert_eq!(state.plans["GMERCHANT"].len(), 1);
        assert_eq!(state.plans["GMERCHANT"][0].billing_amount, 100);
    }

    #[test]
    fn test_subscribe_creates_billing_cycle() {
        let mut state = fresh_state();
        register_basic_plan(&mut state, "GMERCHANT");
        cmd_subscribe(&mut state, "GSUB".to_string(), "GMERCHANT".to_string(), 1, 500);
        let key = "GSUB:GMERCHANT";
        assert!(state.billing_cycles.contains_key(key));
        assert_eq!(state.billing_cycles[key].status, SubscriptionStatus::Active);
        assert_eq!(state.balances["GSUB"], 500);
    }

    #[test]
    fn test_pull_after_cycle_succeeds() {
        let mut state = fresh_state();
        register_basic_plan(&mut state, "GMERCHANT");
        cmd_subscribe(&mut state, "GSUB".to_string(), "GMERCHANT".to_string(), 1, 500);

        // Advance past billing cycle
        cmd_advance(&mut state, 2_592_001);
        cmd_pull(&mut state, "GMERCHANT".to_string(), "GSUB".to_string());

        assert_eq!(state.balances["GSUB"], 400); // 500 - 100
        assert_eq!(state.balances["GMERCHANT"], 100);
        assert_eq!(state.pull_history.len(), 1);
    }

    #[test]
    #[should_panic]
    fn test_pull_before_due_date_fails() {
        let mut state = fresh_state();
        register_basic_plan(&mut state, "GMERCHANT");
        cmd_subscribe(&mut state, "GSUB".to_string(), "GMERCHANT".to_string(), 1, 500);
        // Do NOT advance — pull should fail
        cmd_pull(&mut state, "GMERCHANT".to_string(), "GSUB".to_string());
    }

    #[test]
    fn test_trial_converts_to_active_on_advance() {
        let mut state = fresh_state();
        cmd_register_plan(
            &mut state,
            "GMERCHANT".to_string(),
            2,
            "Trial Plan".to_string(),
            100,
            2_592_000,
            true,
            FREE_TRIAL_DURATION,
        );
        cmd_subscribe(&mut state, "GSUB".to_string(), "GMERCHANT".to_string(), 2, 500);
        assert_eq!(
            state.billing_cycles["GSUB:GMERCHANT"].status,
            SubscriptionStatus::Trial
        );

        // Advance past trial
        cmd_advance(&mut state, FREE_TRIAL_DURATION + 1);
        assert_eq!(
            state.billing_cycles["GSUB:GMERCHANT"].status,
            SubscriptionStatus::Active
        );
    }

    #[test]
    fn test_insufficient_balance_triggers_dunning() {
        let mut state = fresh_state();
        register_basic_plan(&mut state, "GMERCHANT");
        // Subscribe with only 50 tokens — not enough for a 100-token pull
        cmd_subscribe(&mut state, "GSUB".to_string(), "GMERCHANT".to_string(), 1, 50);
        cmd_advance(&mut state, 2_592_001);

        // Pull should fail and set PastDue — we catch the process::exit via a manual check
        let key = "GSUB:GMERCHANT";
        let balance = state.balances.get("GSUB").copied().unwrap_or(0);
        let amount = state.billing_cycles[key].billing_amount;
        assert!(balance < amount, "balance should be insufficient");
    }
}
